### ISSUE TITLE
Why is boolean module not exported?

### ISSUE THREAD

**Issue by jirihon** [mathigon/euclid.js#102]
The `src/boolean.ts` module is the only one which is not exported in `src/index.ts`. Is there any specific reason for that? Or is it just an accidental omission? I would love to use the module :)

**Comment by plegner** [comment]
Some methods (e.g. `union`) are exported as part of the Polygon class, e.g. https://github.com/mathigon/euclid.js/blob/master/src/polygon.ts#L120

However, we can certainly export the other methods, too, publicly. Thanks!

**Comment by jirihon** [comment]
Thank you very much for very fast positive response. @mathigon/euclid is already an excellent library which I love to use.

**Comment by plegner** [comment]
Fixed in `v1.1.1`
