### ISSUE TITLE
Intersection of ray and polygon contains point that does not lie on the ray

### ISSUE THREAD

**Issue by jirihon** [mathigon/euclid.js#103]
When finding intersections of a ray and a polygon, the result may contain point that does not lie on the ray. Try the following code:

```javascript
const polygon = new Polygon(new Point(0, 0), new Point(100, 0), new Point(100, 100), new Point(0, 100), new Point(0, 50));
const ray = new Ray(new Point(50, 50), new Point(100, 50));
console.log(intersections(ray, polygon));
```
The result of the `intersections` function contains `Point(0, 50)` which does not lie on the ray.

I think this happens when there is a polygon vertex that lies on a line coincident with the ray. If `Point(0, 50)` is removed from the *polygon*, the result is valid.

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/euclid.js/commit/757cdf8ccb25aad7c7a2836f6ed71961302ef930 (released as `v1.1.1` on NPM). Thanks!
