### ISSUE TITLE
convert shapes to polygons

### ISSUE THREAD

**Issue by ianstormtaylor** [mathigon/euclid.js#105]
First off, this set of libraries is absolutely brilliant, thank you!

I'm playing around with it for some generative art, and wondering if there is a way to convert shapes like circles, ellipses, etc. into polygons. So that I can do things like distort the points, chop them up, smoothing, etc., etc.

It would be great if there was a `ellipse.polygon(60)` for example which "rasterized" it into a 60-sided polygon.

**Comment by plegner** [comment]
Great ideas, @ianstormtaylor! Here are some examples of how you could achieve this:

```ts
// For circles
const p = Polygon.regular(60, 10)

// For ellipses
import {list} from '@mathigon/core';
const ellipse = new Ellipse(new Point(0, 0), 10, 15);
const q = new Polygon(...list(0, 1, 1/60).map(t => ellipse.at(t)));
```

**Comment by ianstormtaylor** [comment]
Very smart, thanks @plegner!
