### ISSUE TITLE
Finding intersection between LineSegment and Rectangle

### ISSUE THREAD

**Issue by greenbech** [mathigon/euclid.js#134]
Hello, and thanks for this great library!

I wanted to use this library to calculate the intersection between a line segment and a rectangle but was unable to figure out how to do that. The [`intersections` method ](https://github.com/mathigon/euclid.js/blob/master/src/intersection.ts#L134) looked promising, but it does not accept `LineSegment` or `Rectangle` as arguments.

In my particular case, it would always just be one intersection because I want to draw a line from the center of one rectangle to the center of another non-overlapping rectangle, but in general, I guess such a function should return a list of potentially more than one intersection.

**Comment by plegner** [comment]
Hi! Thanks for your interest in euclid.js. The `intersections` method does except euclid's `Rectangle` and `Segment` classes as argument, and you should be able to use it to find intersections between them. I've added a text case here to show how to use it:
https://github.com/mathigon/euclid.js/commit/32be0713e524033be18c80d0f0521a206e454836

Note that line `Segment`s are bounded, while the `Line` class is infinite and could have up to 2 intersections. Hope this helps!

**Comment by greenbech** [comment]
Thanks for the quick reply! The `intersections` method seems to work great after all. I think actually I tried to use the `intersect` method instead previously 😅

A small nitpick to the commit ([32be071](https://github.com/mathigon/euclid.js/commit/32be0713e524033be18c80d0f0521a206e454836)); Should maybe the test case be called "rectangle-segment intersection" instead? :)
