### ISSUE TITLE
Scale center point in ellipse

### ISSUE THREAD

**Issue by burimar** [mathigon/euclid.js#138]
Hello, the method scale on the ellipse does not scale the center point but only the axes. It would be nice if the behavior was the same as in the circle. Many thanks in advance!

      scale(sx: number, sy = sx) {
        return new Ellipse(this.c.scale(sx, sy), this.a * sx, this.b * sy, this.angle);
      }

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/euclid.js/pull/139
