### ISSUE TITLE
Make interface methods take in SimplePoint instead of Point. 

### ISSUE THREAD

**Issue by davjhan** [mathigon/euclid.js#87]
For example, `Point.translate(Point)` should just accept `Point.translate({x:100,y:100})`, which is less verbose than `Point.translate(new Point(100,100))`

**Comment by joshestein** [comment]
Hey @davjhan! Thanks for pointing this out.

You could also use `Point.add()`, which takes a `SimplePoint` as a parameter. Alternatively, you could also use `Point.shift()`, which might be the least verbose option!

**Comment by plegner** [comment]
I've changed the type signature for all `.translate()` methods (not just Points) in https://github.com/mathigon/euclid.js/commit/4d69e6aea4f8b332b09cf51c4b8f36a062f7bc95. This will be published to NPM in our next update. However, the `.shift(x, y)` method might still be simpler in many cases.

Thanks for suggesting this!
